version: "3.7"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: api
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8000:8000
    # uncomment the volume mapping if hot reload is required
    volumes:
      - ./llmapi:/applications/llmapi
    depends_on:
      - postgres

networks:
  llmapi:
    driver: bridge
    name: llmapi
