FROM python:3.10.2-slim

RUN --mount=type=cache,target=/var/lib/apt/list,sharing=locked \
    apt-get update && \
    apt-get install -y g++

WORKDIR "/applications"
COPY requirements.txt /applications/

RUN --mount=type=cache,target=/root/.cache \
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY llmapi/routers/ /applications/llmapi/routers/
COPY llmapi/models/ /applications/llmapi/models/
COPY llmapi/utils/ /applications/llmapi/utils/
COPY llmapi/*.py /applications/llmapi/

ENV PYTHONPATH="/applications"
ENV N_UVICORN_WORKERS=5

EXPOSE 8000

CMD uvicorn llmapi.app:app --reload --workers ${N_UVICORN_WORKERS} --host 0.0.0.0 --port 8000